---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-unfurl
spec:
  template:
    spec:
      containers:
      - name: grafana-unfurl
        startupProbe:
          initialDelaySeconds: 2
          httpGet:
            path: /-/initialized
            port: probes
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /-/healthy
            port: probes
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /-/ready
            port: probes
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 400Mi
            cpu: 100m
        volumeMounts:
        - name: config
          mountPath: /grafana-unfurl/config.yaml
          subPath: config.yaml
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: grafana-unfurl
